apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-to-m3db
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: write-to-m3db
  template:
    metadata:
      labels:
        app: write-to-m3db
    spec:
      imagePullSecrets:
      - name: gcr-json-key1
      containers:
      - image: gcr.io/chrishanna-615-202301281847560/write-to-m3db:v8
        name: write-to-m3db
        ports:
        - containerPort: 80